// <auto-generated />
namespace AlchemicShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_UserRole_tbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_UserRole_tbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202005021730275_add_UserRole_tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
